import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {normalizeEdits} from './liveModel';
import type {ElementEdit,LiveEdits} from './liveModel';
import './live.css';

type History={undo:()=>void;redo:()=>void;begin:()=>void;end:()=>void;canUndo:boolean;canRedo:boolean};
type Props={markup:string;width:number;height:number;edits?:LiveEdits;onChange:(edits:LiveEdits)=>void;history:History;children:(id:string)=>React.ReactNode;onAdvanced:()=>void;onAdd:(kind:'text'|'shape')=>string;onDelete:(id:string)=>void};
type Box={x:number;y:number;w:number;h:number;matrix:string;handle?:number};
export function LiveEditor({markup,width,height,edits:raw,onChange,history,children,onAdvanced,onAdd,onDelete}:Props){
  const edits=normalizeEdits(raw),[selected,select]=useState(''),[zoom,setZoom]=useState(1),[snap,setSnap]=useState(true),[panel,setPanel]=useState(true),[box,setBox]=useState<Box|null>(null),[appearance,setAppearance]=useState<Record<string,string>>({}),[fitWidth,setFitWidth]=useState(400),[layers,setLayers]=useState<{id:string;label:string}[]>([]);
  const stage=useRef<HTMLDivElement>(null),canvas=useRef<HTMLDivElement>(null),editor=useRef<HTMLDivElement>(null),gesture=useRef<{id:string;pointer:number;x:number;y:number;edit:ElementEdit;box:Box;mode:string;inverse:DOMMatrix;original?:ElementEdit}|null>(null),latest=useRef({edits,onChange,history});latest.current={edits,onChange,history};
  const e=edits[selected]||{},locked=!!e.locked;
  const patch=(p:Partial<ElementEdit>)=>onChange({...edits,[selected]:{...e,...p,...(box?{cx:box.x+box.w/2,cy:box.y+box.h/2}:{})}});
  const measure=()=>{const svg=canvas.current?.querySelector('svg'),nodes=svg?.querySelectorAll<SVGGElement>('[data-live-id]');
    if(!svg||!nodes)return;setLayers(Array.from(nodes).map(n=>({id:n.dataset.liveId!,label:n.dataset.liveLabel!})));
    const node=Array.from(nodes).find(n=>n.dataset.liveId===selected);if(!node){setBox(null);return;}
    const own=Array.from(node.querySelectorAll('*')).filter(n=>n.closest('[data-live-id]')===node),shape=own.find(n=>n.hasAttribute('fill')&&n.getAttribute('fill')!=='none'&&n.tagName!=='text'&&n.tagName!=='tspan'),border=own.find(n=>n.hasAttribute('stroke')),text=own.find(n=>n.tagName==='text'),rect=own.find(n=>n.tagName==='rect'&&n.hasAttribute('rx'));setAppearance({hasShape:String(!!shape),hasBorder:String(!!border),hasText:String(!!text),hasRadius:String(!!rect),fill:shape?.getAttribute('fill')||'#18232b',stroke:border?.getAttribute('stroke')||'#eee6da',strokeWidth:border?.getAttribute('stroke-width')||'1.5',radius:rect?.getAttribute('rx')||'0',textColor:text?.getAttribute('fill')||'#213749',fontSize:text?.getAttribute('font-size')||'16',fontWeight:text?.getAttribute('font-weight')||'700',letterSpacing:text?.getAttribute('letter-spacing')||'0'});
    try{const b=node.getBBox(),root=svg.getCTM(),m=node.getCTM();setBox({x:b.x,y:b.y,w:b.width,h:b.height,matrix:root&&m?root.inverse().multiply(m).toString():'',handle:m?14/Math.max(.01,Math.hypot(m.a,m.b)):14});}catch{setBox(null);}
  };
  useLayoutEffect(measure,[markup,selected,zoom]);
  useEffect(()=>{const resize=new ResizeObserver(()=>{const el=stage.current;if(el)setFitWidth(Math.max(100,Math.min(el.clientWidth-52,(el.clientHeight-90)*width/height)));measure();});if(stage.current)resize.observe(stage.current);return()=>resize.disconnect();},[selected,width,height,panel]);
  const point=(ev:React.PointerEvent)=>{const svg=canvas.current?.querySelector('svg');const m=svg?.getScreenCTM();return m?new DOMPoint(ev.clientX,ev.clientY).matrixTransform(m.inverse()):new DOMPoint();};
  const start=(ev:React.PointerEvent,mode='move')=>{
    if(ev.button!==0)return;
    const target=(ev.target as Element).closest('[data-live-id]') as SVGGElement|null,id=mode==='move'?target?.dataset.liveId:selected;
    if(!id){select('');return;}select(id);setPanel(true);
    const node=Array.from(canvas.current!.querySelectorAll<SVGGElement>('[data-live-id]')).find(n=>n.dataset.liveId===id);
    if(!node||edits[id]?.locked)return;
    const b=node.getBBox(),inverse=(node.parentElement as unknown as SVGGraphicsElement).getScreenCTM()!.inverse(),p=new DOMPoint(ev.clientX,ev.clientY).matrixTransform(inverse);gesture.current={id,pointer:ev.pointerId,x:p.x,y:p.y,edit:{...edits[id],cx:b.x+b.width/2,cy:b.y+b.height/2},box:{x:b.x,y:b.y,w:b.width,h:b.height,matrix:''},mode,inverse,original:edits[id]};
    history.begin();ev.currentTarget.setPointerCapture(ev.pointerId);ev.preventDefault();
  };
  const move=(ev:React.PointerEvent)=>{const g=gesture.current;if(!g||g.pointer!==ev.pointerId)return;const p=new DOMPoint(ev.clientX,ev.clientY).matrixTransform(g.inverse),dx=p.x-g.x,dy=p.y-g.y,base=g.edit;
    const round=(n:number)=>snap?Math.round(n/5)*5:n;let change:ElementEdit;
    if(g.mode==='resize'){const angle=(base.rotation??0)*Math.PI/180,localX=dx*Math.cos(angle)+dy*Math.sin(angle),localY=-dx*Math.sin(angle)+dy*Math.cos(angle);let sx=Math.max(.1,Math.min(5,(base.sx??1)+localX*2/Math.max(1,g.box.w))),sy=Math.max(.1,Math.min(5,(base.sy??1)+localY*2/Math.max(1,g.box.h)));if(ev.shiftKey)sy=sx;change={sx,sy};}
    else if(g.mode==='rotate'){const cx=(base.cx??0)+(base.x??0),cy=(base.cy??0)+(base.y??0),angle=(Math.atan2(p.y-cy,p.x-cx)-Math.atan2(g.y-cy,g.x-cx))*180/Math.PI+(base.rotation??0);change={rotation:Math.max(-180,Math.min(180,snap?Math.round(angle/15)*15:angle))};}
    else change={x:round((base.x??0)+dx),y:round((base.y??0)+dy)};
    const current=latest.current;current.onChange({...current.edits,[g.id]:{...base,...change}});
  };
  const finish=(ev:React.PointerEvent,cancel=false)=>{const g=gesture.current;if(!g||g.pointer!==ev.pointerId)return;if(cancel){const next={...latest.current.edits};if(g.original)next[g.id]=g.original;else delete next[g.id];latest.current.onChange(next);}gesture.current=null;history.end();};
  useEffect(()=>{const key=(ev:KeyboardEvent)=>{if(!editor.current?.contains(document.activeElement)||/INPUT|TEXTAREA|SELECT/.test((ev.target as Element).tagName))return;
    const h=latest.current.history;if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='z'){ev.preventDefault();ev.shiftKey?h.redo():h.undo();return;}
    if(ev.key==='Escape'){select('');return;}if(!selected||locked)return;
    const delta=ev.shiftKey?10:1;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(ev.key)){ev.preventDefault();patch({x:(e.x??0)+(ev.key==='ArrowRight'?delta:ev.key==='ArrowLeft'?-delta:0),y:(e.y??0)+(ev.key==='ArrowDown'?delta:ev.key==='ArrowUp'?-delta:0)});}
    if(ev.key==='Delete'||ev.key==='Backspace'){ev.preventDefault();patch({hidden:true});}
  };window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[selected,e,box,locked]);
  const number=(label:string,key:keyof ElementEdit,value:number,min:number,max:number,step=1)=><label>{label}<input type="number" value={Number(value.toFixed(2))} min={min} max={max} step={step} disabled={locked} onChange={ev=>{if(ev.target.value!==''&&Number.isFinite(ev.target.valueAsNumber))patch({[key]:Math.max(min,Math.min(max,ev.target.valueAsNumber))});}}/></label>;
  const color=(label:string,key:keyof ElementEdit,fallback:string)=><label>{label}<input type="color" value={String(e[key]??(/^#[0-9a-f]{6}$/i.test(appearance[key]||'')?appearance[key]:fallback))} disabled={locked} onChange={ev=>patch({[key]:ev.target.value})}/></label>;
  return <div className="liveEditor" ref={editor}>
    <div className="liveToolbar" role="toolbar" aria-label="Strumenti di modifica"><b>Modifica sulla grafica</b><button onClick={history.undo} disabled={!history.canUndo} aria-label="Annulla">↶</button><button onClick={history.redo} disabled={!history.canRedo} aria-label="Ripeti">↷</button><label className="liveZoom">Zoom<select aria-label="Zoom grafica" value={zoom} onChange={ev=>setZoom(Number(ev.target.value))}>{[.5,.75,1,1.5,2,3].map(z=><option key={z} value={z}>{z===1?'Adatta':`${z*100}%`}</option>)}</select></label><label className="liveSnap"><input type="checkbox" checked={snap} onChange={ev=>setSnap(ev.target.checked)}/>Allinea</label><button onClick={()=>setPanel(v=>!v)} aria-expanded={panel}>Elementi</button><button onClick={()=>{select(onAdd('text'));setPanel(true);}}>+ Testo</button><button onClick={()=>{select(onAdd('shape'));setPanel(true);}}>+ Forma</button><button onClick={onAdvanced}>Avanzate</button></div>
    <div className="liveBody"><div className="liveStage" ref={stage} tabIndex={0} aria-label="Area di modifica: seleziona un elemento e usa le frecce per spostarlo">
      <p className="liveHint">Tocca un blocco per modificarlo · trascina per spostarlo · usa le maniglie per dimensione e rotazione</p>
      <div className="liveCanvas" ref={canvas} style={{width:`${fitWidth*zoom}px`,maxWidth:'none',aspectRatio:`${width}/${height}`}} onPointerDown={start} onPointerMove={move} onPointerUp={ev=>finish(ev)} onPointerCancel={ev=>finish(ev,true)} onLostPointerCapture={ev=>finish(ev,true)} onDoubleClick={()=>editor.current?.querySelector<HTMLTextAreaElement>('.liveContent textarea')?.focus()}>
        <div className="liveArtwork" dangerouslySetInnerHTML={{__html:markup}}/>
        <svg className="liveOverlay" viewBox={`0 0 ${width} ${height}`} aria-hidden="true">{box&&!e.hidden&&<g transform={box.matrix}><rect className="liveSelection" x={box.x} y={box.y} width={box.w} height={box.h}/>{!locked&&<><rect className="liveHandle" data-live-handle="resize" x={box.x+box.w-(box.handle??9)} y={box.y+box.h-(box.handle??9)} width={(box.handle??9)*2} height={(box.handle??9)*2} onPointerDown={ev=>{ev.stopPropagation();start(ev,'resize');}}/><line className="liveSelection" x1={box.x+box.w/2} x2={box.x+box.w/2} y1={box.y} y2={box.y-(box.handle??10)*3}/><circle className="liveHandle" data-live-handle="rotate" cx={box.x+box.w/2} cy={box.y-(box.handle??10)*3} r={box.handle??10} onPointerDown={ev=>{ev.stopPropagation();start(ev,'rotate');}}/></>}</g>}</svg>
      </div>
    </div>{panel&&<aside className="liveInspector" aria-label="Elemento selezionato"><label>Seleziona un elemento<select aria-label="Seleziona un elemento" value={selected} onChange={ev=>select(ev.target.value)}><option value="">Scegli dalla grafica o dall’elenco</option>{layers.map(l=><option key={l.id} value={l.id}>{l.label}{edits[l.id]?.hidden?' · nascosto':''}{edits[l.id]?.locked?' · bloccato':''}</option>)}</select></label>
      {selected?<><header><strong>{layers.find(l=>l.id===selected)?.label}</strong><button aria-label="Deseleziona" onClick={()=>select('')}>×</button></header><div className="liveActions"><button onClick={()=>patch({locked:!locked})}>{locked?'Sblocca':'Blocca'}</button><button disabled={locked} onClick={()=>patch({hidden:!e.hidden})}>{e.hidden?'Mostra':'Nascondi'}</button><button disabled={locked} onClick={()=>{const next={...edits};delete next[selected];onChange(next);}}>Ripristina</button></div>{selected.startsWith('custom-')&&<button disabled={locked} onClick={()=>{onDelete(selected);select('');}}>Elimina elemento aggiunto</button>}<fieldset disabled={locked} className="liveContent">{children(selected)}</fieldset>
      <details open><summary>Posizione e dimensione</summary><div className="liveGrid">{number('Sposta a destra / sinistra','x',e.x??0,-3200,3200)}{number('Sposta in alto / basso','y',e.y??0,-3200,3200)}{number('Larghezza (×)','sx',e.sx??1,.1,5,.05)}{number('Altezza (×)','sy',e.sy??1,.1,5,.05)}{number('Rotazione (°)','rotation',e.rotation??0,-180,180)}{number('Opacità (0–1)','opacity',e.opacity??1,0,1,.05)}</div><div className="liveActions"><button disabled={locked} onClick={()=>patch({x:width/2-(box?.x??0)-(box?.w??0)/2})}>Centra ↔</button><button disabled={locked} onClick={()=>patch({y:height/2-(box?.y??0)-(box?.h??0)/2})}>Centra ↕</button></div></details>
      {(appearance.hasShape==='true'||appearance.hasBorder==='true')&&<details><summary>Colori e bordi</summary><div className="liveGrid">{appearance.hasShape==='true'&&color('Fondo','fill','#18232b')}{appearance.hasBorder==='true'&&color('Bordo','stroke','#eee6da')}{appearance.hasBorder==='true'&&number('Spessore bordo','strokeWidth',e.strokeWidth??Number(appearance.strokeWidth),0,20,.5)}{appearance.hasRadius==='true'&&number('Angoli arrotondati','radius',e.radius??Number(appearance.radius),0,100)}</div></details>}
      {appearance.hasText==='true'&&<details><summary>Stile del testo</summary><div className="liveGrid">{color('Colore testo','textColor','#213749')}{number('Grandezza testo','fontSize',e.fontSize??Number(appearance.fontSize),8,80)}{number('Spessore testo','fontWeight',e.fontWeight??Number(appearance.fontWeight),300,900,100)}{number('Spazio tra lettere','letterSpacing',e.letterSpacing??Number(appearance.letterSpacing),-2,12,.5)}</div><label>Carattere<select disabled={locked} value={e.fontFamily??'Arial'} onChange={ev=>patch({fontFamily:ev.target.value})}>{['Arial','Inter','Trebuchet MS','Verdana','Georgia','Impact','Courier New'].map(f=><option key={f}>{f}</option>)}</select></label></details>}
      <details><summary>Ordine degli elementi</summary><div className="liveActions"><button disabled={locked} onClick={()=>patch({order:Math.max(0,...Object.values(edits).map(v=>v.order??0))+1})}>Porta davanti</button><button disabled={locked} onClick={()=>patch({order:Math.min(0,...Object.values(edits).map(v=>v.order??0))-1})}>Porta dietro</button></div><small>L’ordine cambia tra elementi dello stesso gruppo.</small></details></>:<p>Seleziona sulla grafica o nell’elenco. Anche gli elementi nascosti possono essere selezionati e riattivati.</p>}
    </aside>}</div>
  </div>;
}
