import React, { useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import jsPDF from 'jspdf';
import './styles.css';

type CardType='fighter'|'location'|'action'|'extraFighter'|'objective'|'token';
type Detail={label:string;value:string;icon?:string};
type Card={id:string;type:CardType;name:string;scope:string;scopeColor:string;cost?:string;rarity?:string;meta:Detail[];effects:Detail[];stats:{kind:string;value:string}[];art?:string};
const TYPES:Record<CardType,string>={fighter:'Combattente',location:'Luogo',action:'Azione',extraFighter:'ExtraCombattente',objective:'Obiettivo',token:'Token'};
const DEFAULT:Card={id:'KRT-001',type:'fighter',name:'Nuova carta',scope:'Informatica',scopeColor:'#1d5c6b',cost:'3',rarity:'Non comune',meta:[{label:'Archetipo',value:'Satirico'},{label:'Velocità',value:'Media'}],effects:[{label:'EFFETTO',value:'Inserisci qui l’effetto principale.'},{label:'Lore',value:'Descrizione breve opzionale.'}],stats:[{kind:'ATK',value:'3'},{kind:'RES',value:'4'},{kind:'PRF',value:'2'}]};
const scopeDefault:Record<string,string>={Informatica:'#1d5c6b',Economia:'#3f6b3a',Medicina:'#a8324a',Ingegneria:'#9a5b17',Sportivi:'#4a3a86',Media:'#a8296e'};
function preset(type:CardType):Card{ const c={...DEFAULT,type,name:`Nuovo ${TYPES[type]}`,meta:[...DEFAULT.meta],effects:[...DEFAULT.effects],stats:[...DEFAULT.stats]}; if(type==='location') c.stats=[{kind:'RES',value:'5'}]; if(type==='action'){c.meta=[{label:'Tipo',value:'Istantanea'},{label:'Velocità',value:'Veloce'},{label:'Settabile',value:'Sì'}];c.stats=[];c.effects=[{label:'EFFETTO',value:'Descrivi chiaramente l’azione.'}];} if(type==='extraFighter'){c.cost='2 materiali';c.meta=[{label:'Requisito',value:'Controlla 2 Luoghi'},{label:'Archetipo',value:'Speciale'}];} if(type==='objective'){delete c.cost;c.meta=[];c.stats=[{kind:'PV',value:'3'}];c.effects=[{label:'CONDIZIONE',value:'Descrivi la condizione obiettivo.'},{label:'Lore',value:'Testo opzionale.'}];} if(type==='token'){delete c.cost;c.meta=[{label:'Token',value:'Combattente'}];} return c; }
function useLocalStore(){const [cards,setCards]=useState<Card[]>(()=>{try{return JSON.parse(localStorage.getItem('kritoma.cards')||localStorage.getItem('kritomia.cards')||'[]')}catch{return[]}}); const save=(next:Card[])=>{setCards(next);localStorage.setItem('kritoma.cards',JSON.stringify(next));};return {cards,save};}
function svg(card:Card){
 const meta=card.meta.map((m,i)=>`<g transform="translate(${58+i*(474/Math.max(card.meta.length,1))},502)"><rect width="${474/Math.max(card.meta.length,1)-8}" height="46" rx="22" fill="${card.scopeColor}" fill-opacity=".95" stroke="#222" stroke-width="2"/><text x="18" y="19" fill="#fff" font-size="12" font-family="Arial" font-weight="700">${esc(m.label)}</text><text x="18" y="35" fill="#fff" font-size="13" font-family="Arial">${esc(m.value)}</text></g>`).join('');
 const eff=card.effects.map((e,i)=>`<text x="62" y="${590+i*30}" fill="#252525" font-size="${i===0?16:13}" font-family="Arial" font-weight="${i===0?700:400}">${esc(e.label)}: ${esc(e.value)}</text>`).join('');
 const statW=card.stats.length?310/card.stats.length:0; const stats=card.stats.map((s,i)=>`<g transform="translate(${48+i*statW},770)"><rect width="${statW-8}" height="54" rx="12" fill="${i===0?'#8f2030':i===1?'#145f86':'#9a6718'}" stroke="#f1e7d2" stroke-width="3"/><text x="18" y="34" fill="white" font-size="17" font-family="Arial" font-weight="700">${esc(s.kind)} ${esc(s.value)}</text></g>`).join('');
 const artwork=card.art?`<image href="${card.art}" x="42" y="118" width="546" height="370" preserveAspectRatio="xMidYMid slice"/>`:'';
 const cost=card.type==='token'||card.type==='objective'?'':`<circle cx="78" cy="70" r="46" fill="#f2eee5" stroke="#182634" stroke-width="8"/><text x="78" y="79" text-anchor="middle" font-size="24" font-family="Arial" font-weight="700" fill="#182634">${esc(card.cost||'')}</text>`;
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 630 880" width="630" height="880"><rect width="630" height="880" fill="#fff"/><rect x="25" y="25" width="580" height="830" rx="28" fill="#efe9dc" stroke="#1a2732" stroke-width="6"/><path d="M35 180 Q70 105 150 105 H560 Q595 130 595 180 V485 Q575 455 555 475 Q585 535 595 565 V745 H35 V565 Q45 535 75 475 Q55 455 35 485 Z" fill="${card.scopeColor}" fill-opacity=".23"/><rect x="42" y="118" width="546" height="370" rx="50" fill="#fff" stroke="#1f2a33" stroke-width="4"/>${artwork}<rect x="120" y="38" width="465" height="66" rx="24" fill="#f3eee4" stroke="#1f2a33" stroke-width="4"/><text x="155" y="79" font-size="26" font-family="Arial" font-weight="700" fill="#1d2730">${esc(card.name)}</text>${cost}<rect x="50" y="558" width="530" height="180" rx="28" fill="#f4efe5" stroke="#1f2a33" stroke-width="4"/>${meta}${eff}${stats}<g transform="translate(374 770)"><rect width="208" height="54" rx="12" fill="#202a33" stroke="#eee3cf" stroke-width="3"/><text x="18" y="34" fill="#ddd" font-size="16" font-family="Arial" font-weight="700">ID ${esc(card.id)}</text></g></svg>`;
}
function esc(s:any){return String(s??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'} as any)[c]);}
function App(){const store=useLocalStore();const [card,setCard]=useState<Card>(()=>store.cards[0]||DEFAULT);const inputRef=useRef<HTMLInputElement>(null);const markup=useMemo(()=>svg(card),[card]);const update=(p:Partial<Card>)=>setCard({...card,...p}); const addMeta=()=>update({meta:[...card.meta,{label:'Campo',value:'Valore'}]}); const addEffect=()=>update({effects:[...card.effects,{label:'Dettaglio',value:'Testo'}]}); const save=()=>{const next=[...store.cards.filter(c=>c.id!==card.id),card];store.save(next)};
 const exportSvg=()=>download(`${card.id}.svg`,new Blob([markup],{type:'image/svg+xml'})); const exportPng=async()=>{const blob=new Blob([markup],{type:'image/svg+xml'});const url=URL.createObjectURL(blob);const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=1260;c.height=1760;const ctx=c.getContext('2d')!;ctx.drawImage(img,0,0,c.width,c.height);c.toBlob(b=>b&&download(`${card.id}.png`,b),'image/png');URL.revokeObjectURL(url)};img.src=url}; const exportPdf=async()=>{const blob=new Blob([markup],{type:'image/svg+xml'});const url=URL.createObjectURL(blob);const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=1890;c.height=2640;c.getContext('2d')!.drawImage(img,0,0,c.width,c.height);const pdf=new jsPDF({orientation:'portrait',unit:'mm',format:[63,88]});pdf.addImage(c.toDataURL('image/png'),'PNG',0,0,63,88);pdf.save(`${card.id}-print.pdf`);URL.revokeObjectURL(url)};img.src=url};
 return <div className="app"><aside><h1>Kritoma Card Editor</h1><label>Tipologia<select value={card.type} onChange={e=>setCard(preset(e.target.value as CardType))}>{Object.entries(TYPES).map(([k,v])=><option value={k}>{v}</option>)}</select></label><label>Nome<input value={card.name} onChange={e=>update({name:e.target.value})}/></label><label>ID<input value={card.id} onChange={e=>update({id:e.target.value})}/></label><label>Ambito<select value={card.scope} onChange={e=>update({scope:e.target.value,scopeColor:scopeDefault[e.target.value]||card.scopeColor})}>{Object.keys(scopeDefault).map(x=><option>{x}</option>)}</select></label><label>Colore ambito<input type="color" value={card.scopeColor} onChange={e=>update({scopeColor:e.target.value})}/></label>{card.type!=='token'&&card.type!=='objective'&&<label>Costo / materiali<input value={card.cost||''} onChange={e=>update({cost:e.target.value})}/></label>}<section><div className="sectionHead"><b>Slot sotto illustrazione</b><button onClick={addMeta}>+</button></div>{card.meta.map((m,i)=><div className="row"><input value={m.label} onChange={e=>{const a=[...card.meta];a[i]={...m,label:e.target.value};update({meta:a})}}/><input value={m.value} onChange={e=>{const a=[...card.meta];a[i]={...m,value:e.target.value};update({meta:a})}}/><button onClick={()=>update({meta:card.meta.filter((_,j)=>j!==i)})}>×</button></div>)}</section><section><div className="sectionHead"><b>Effetti / sottocampi</b><button onClick={addEffect}>+</button></div>{card.effects.map((m,i)=><div className="row"><input value={m.label} onChange={e=>{const a=[...card.effects];a[i]={...m,label:e.target.value};update({effects:a})}}/><textarea value={m.value} onChange={e=>{const a=[...card.effects];a[i]={...m,value:e.target.value};update({effects:a})}}/><button onClick={()=>update({effects:card.effects.filter((_,j)=>j!==i)})}>×</button></div>)}</section><section><b>Statistiche</b>{card.stats.map((s,i)=><div className="row"><input value={s.kind} onChange={e=>{const a=[...card.stats];a[i]={...s,kind:e.target.value};update({stats:a})}}/><input value={s.value} onChange={e=>{const a=[...card.stats];a[i]={...s,value:e.target.value};update({stats:a})}}/></div>)}</section><input ref={inputRef} hidden type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>update({art:String(r.result)});r.readAsDataURL(f)}}/><button onClick={()=>inputRef.current?.click()}>Carica illustrazione</button><div className="actions"><button onClick={save}>Salva cache</button><button onClick={exportSvg}>SVG</button><button onClick={exportPng}>PNG</button><button onClick={exportPdf}>PDF stampa</button></div><small>Cache locale: {store.cards.length} carte salvate</small></aside><main><div className="preview" dangerouslySetInnerHTML={{__html:markup}}/></main></div>}
function download(name:string,blob:Blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
createRoot(document.getElementById('root')!).render(<App/>);
